name: gen_lang
description: >-
  gen_lang is a dart library for internationalization. Extracts messages
  to generate dart files required by Intl
version: 0.1.1
author: King Wu (@kw101) <king.wuff101@gmail.com>
homepage: https://github.com/KingWu/gen_lang

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  args: '>=0.12.1 <2.0.0'
  path: '>=0.9.0 <2.0.0'
  ansicolor: ^1.0.2